<a href="https://colab.research.google.com/github/anp2/Declarative-Pipeline/blob/master/EcommProj.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [10]:
from google.colab import files

uploaded = files.upload()

Saving CustomersData.csv to CustomersData.csv
Saving Tax_amount.xlsx to Tax_amount.xlsx
Saving Online_Sales.csv to Online_Sales.csv
Saving Marketing_Spend.csv to Marketing_Spend.csv
Saving Discount_Coupon.csv to Discount_Coupon.csv

In [12]:
customer_df = pd.read_csv('CustomersData.csv')

disc_coupon_df = pd.read_csv('Discount_Coupon.csv')

sales_df = pd.read_csv('Online_Sales.csv')

marketing_df = pd.read_csv('Marketing_Spend.csv')

tax_df = pd.read_excel('Tax_amount.xlsx')

In [13]:
print("Customer Data")
display(customer_df.head())

print("Discount Coupon")
display(disc_coupon_df.head())

print("Online Sales")
display(sales_df.head())

print("Marketing Spend")
display(marketing_df.head())

print("Tax Data")
display(tax_df.head())

Customer Data

   CustomerID Gender    Location  Tenure_Months
0       17850      M     Chicago             12
1       13047      M  California             43
2       12583      M     Chicago             33
3       13748      F  California             30
4       15100      M  California             49

Discount Coupon

  Month Product_Category Coupon_Code  Discount_pct
0   Jan          Apparel      SALE10            10
1   Feb          Apparel      SALE20            20
2   Mar          Apparel      SALE30            30
3   Jan         Nest-USA      ELEC10            10
4   Feb         Nest-USA      ELEC20            20

Online Sales

,CustomerID,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,Quantity,Avg_Price,Delivery_Charges,Coupon_Status
0,17850,16679,1/1/2019,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1,153.71,6.5,Used
1,17850,16680,1/1/2019,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1,153.71,6.5,Used
2,17850,16681,1/1/2019,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,1,2.05,6.5,Used
3,17850,16682,1/1/2019,GGOEGAAB010516,Google Men's 100% Cotton Short Sleeve Hero Tee...,Apparel,5,17.53,6.5,Not Used
4,17850,16682,1/1/2019,GGOEGBJL013999,Google Canvas Tote Natural/Navy,Bags,1,16.50,6.5,Used

Marketing Spend

       Date  Offline_Spend  Online_Spend
0  1/1/2019           4500       2424.50
1  1/2/2019           4500       3480.36
2  1/3/2019           4500       1576.38
3  1/4/2019           4500       2928.55
4  1/5/2019           4500       4055.30

Tax Data

  Product_Category   GST
0         Nest-USA  0.10
1           Office  0.10
2          Apparel  0.18
3             Bags  0.18
4        Drinkware  0.18

In [14]:
print("Customer Data:", customer_df.shape)

print("Doscount Coupon:", disc_coupon_df.shape)

print("Online Sales:", sales_df.shape)

print("Marketing Spend:", marketing_df.shape)

print("Tax Data:", tax_df.shape)

Customer Data: (1468, 4)
Doscount Coupon: (204, 4)
Online Sales: (52924, 10)
Marketing Spend: (365, 3)
Tax Data: (20, 2)

In [15]:
customer_df.info()

disc_coupon_df.info()

sales_df.info()

marketing_df.info()

tax_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1468 entries, 0 to 1467
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CustomerID     1468 non-null   int64
 1   Gender         1468 non-null   object
 2   Location       1468 non-null   object
 3   Tenure_Months  1468 non-null   int64
dtypes: int64(2), object(2)
memory usage: 46.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Month             204 non-null    object
 1   Product_Category  204 non-null    object
 2   Coupon_Code       204 non-null    object
 3   Discount_pct      204 non-null    int64
dtypes: int64(1), object(3)
memory usage: 6.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52924 entries, 0 to 52923
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   CustomerID           52924 non-null  int64
 1   Transaction_ID       52924 non-null  int64
 2   Transaction_Date     52924 non-null  object
 3   Product_SKU          52924 non-null  object
 4   Product_Description  52924 non-null  object
 5   Product_Category     52924 non-null  object
 6   Quantity             52924 non-null  int64
 7   Avg_Price            52924 non-null  float64
 8   Delivery_Charges     52924 non-null  float64
 9   Coupon_Status        52924 non-null  object
dtypes: float64(2), int64(3), object(5)
memory usage: 4.0+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           365 non-null    object
 1   Offline_Spend  365 non-null    int64
 2   Online_Spend   365 non-null    float64
dtypes: float64(1), int64(1), object(1)
memory usage: 8.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Product_Category  20 non-null     object
 1   GST               20 non-null     float64
dtypes: float64(1), object(1)
memory usage: 452.0+ bytes

In [16]:
print(customer_df.dtypes)

print(disc_coupon_df.dtypes)

print(sales_df.dtypes)

print(marketing_df.dtypes)

print(tax_df.dtypes)

CustomerID        int64
Gender           object
Location         object
Tenure_Months     int64
dtype: object
Month               object
Product_Category    object
Coupon_Code         object
Discount_pct         int64
dtype: object
CustomerID               int64
Transaction_ID           int64
Transaction_Date        object
Product_SKU             object
Product_Description     object
Product_Category        object
Quantity                 int64
Avg_Price              float64
Delivery_Charges       float64
Coupon_Status           object
dtype: object
Date              object
Offline_Spend      int64
Online_Spend     float64
dtype: object
Product_Category     object
GST                 float64
dtype: object